@rem Automatically generated by Amaranth 0.4.dev21+gdb49294. Do not edit.

if defined NMIGEN_ENV_ICESTORM call %NMIGEN_ENV_ICESTORM%
if defined AMARANTH_ENV_IceStorm call %AMARANTH_ENV_IceStorm%
if [%YOSYS%] equ [""] set YOSYS=
if [%YOSYS%] equ [] set YOSYS=yosys
if [%NEXTPNR_ICE40%] equ [""] set NEXTPNR_ICE40=
if [%NEXTPNR_ICE40%] equ [] set NEXTPNR_ICE40=nextpnr-ice40
if [%ICEPACK%] equ [""] set ICEPACK=
if [%ICEPACK%] equ [] set ICEPACK=icepack
%YOSYS% -l top.rpt top.ys || exit /b
%NEXTPNR_ICE40% --log top.tim --up5k --package sg48 --json top.json --pcf top.pcf --asc top.asc || exit /b
%ICEPACK% -v top.asc top.bin || exit /b